<?php// 接口管理的文件
class JinbibuyAction extends InterAction {	protected $online_status = 1;  //接口是否需要判断用户在线	
	public function buy(){		header("Content-type:text/html;charset=utf-8");
		$check = $this->check_sign();		if ($check['status'] == 1){
				$ordercode = $check['info']['ordercode'];				$user_id = $check['info']['user_id'];
				//获取用户信息				$table1 = M(MYTABLE_PRIFIX."user_info");
				$user = $table1->where("user_id=".$user_id)->find();				$buyer_nick = !empty($user['nickname']) ? $user['nickname'] : $user['nick_name'];				//获取用户钻石购买日志				$table2 = M(MYTABLE_PRIFIX."log_mall_diamond_log");
				$order = $table2->where("ordercode='$ordercode'")->find();
				//判断非空				if (empty($ordercode) && strlen($ordercode)!=18){					return $this->answerResquest('-1','输入异常，请联系客服');				}								//判断订单是否存在				$total = $table2->where("status=1 and ordercode='$ordercode'")->count('id');				if ($total < 1){					return $this->answerResquest('-1','抱歉,此商品已售出或下架~');
				}					//判断用户钻石是否足够兑换				if ($user['diamond'] < $order['diamond']){					return $this->answerResquest('-1','您钻石不足,请充值后再试~');
				}								//更新金币订单				$seller = $table1->where("user_id=".$order['user_id'])->find();				$seller_diamond = $seller['diamond'] + $order['diamond'];				$data = array();				$data['diamond_before'] = $seller['diamond'];				$data['diamond_after'] = $seller_diamond;				$data['buyer_id'] = $user_id;				$data['buyer_nick'] = $buyer_nick;				$data['status'] = 2;				$result = $table2->where("ordercode='$ordercode' and status=1")->save($data);
				if ($result > 0){					$buyer_diamond = $user['diamond'] - $order['diamond'];					$buyer_gold = $user['gold'] + $order['gold'];								//给买家增加金币，减钻石					$data = array();					$data['gold'] = array('exp','gold+'.$order['gold']);					$data['diamond'] = array('exp','diamond-'.$order['diamond']);					$result = $table1->where("user_id=".$user_id." and ".$order['diamond'].">0"." and diamond>=".$order['diamond']." and ".$order['gold'].">0")->limit(1)->save($data);										if ($result <= 0){						return $this->answerResquest('-1','操作异常，请联系客服');
					}
										//给卖家增加钻石					$data = array();					$data['diamond'] = array('exp','diamond+'.$order['diamond']);					$result = $table1->where("user_id=".$order['user_id']." and ".$order['diamond'].">0")->limit(1)->save($data);
					//插入金币日志					$table4 = M(MYTABLE_PRIFIX."log_gold_change_log_".date("Ym"));					$arr = array();					$arr['user_id'] = $user_id;					$arr['curtime'] = time();					$arr['date'] = date("Y-m-d H:i:s");					$arr['module'] = 26;					$arr['beforegold'] = $user['gold'];					$arr['aftergold'] = $buyer_gold;					$arr['changegold'] = $order['gold'];					$arr['taxgold'] = 0;					$arr['roomid'] = 0;					$arr['memo'] = "金币兑换钻石(购买)";					$result = $table4->add($arr);
					//生成订单备注					$table3 = M(MYTABLE_PRIFIX."log_mall_diamond_info");					$data = array();					$data['ordercode'] = $ordercode;					$data['buyer_id'] = $user_id;					$data['buyer_nick'] = $buyer_nick;					$data['diamond'] = $order['diamond'];					$data['diamond_before'] = $user['diamond'];					$data['diamond_after'] = $buyer_diamond;					$data['gold'] = $order['gold'];					$data['gold_before'] = $user['gold'];					$data['gold_after'] = $buyer_gold;					$data['addtime'] = time();					$result = $table3->add($data);
					//PUSH消息及邮件					//插入邮件					$table5 = M(MYTABLE_PRIFIX."user_email");					$showgold = round($order['gold'] / 10000);					$arr = array();					$arr['user_id'] = $order['user_id'];					$arr['email_type'] = 5;					$arr['is_read'] = 0;					$arr['content'] = "玩家".$buyer_nick."买走了您".$showgold."万金币,您获得".$order['diamond']."钻石";					$arr['opera_date'] = date("Y-m-d H:i;s");					$notice_id = $table5->add($arr);								//通知服务器					$buydiamond = -$order['diamond'];					$url = DB_HOST."/Pay/jbmall.php?sellid=".$order['user_id']."&buyid=".$user_id."&type=7&index=2&email=".urlencode($arr['content']);					$server_status = curlGET($url);					$len = strlen($server_status) - 3;					$status = substr($server_status, $len, 1);					$notice_status = ($status==1) ? 1 : 0;										$table6 = M(MYTABLE_PRIFIX."log_mall_diamond_notice");					$arr = array();					$arr['ordercode'] = $ordercode;					$arr['notice_id'] = $notice_id;					$arr['notice_url'] = $url;					$arr['notice_num'] = 1;					$arr['notice_time'] = time();					$arr['notice_status'] = $notice_status;					$result = $table6->add($arr);
					$result0 = array();					$result0['status'] = 1;					$result0['gold'] = (int)$order['gold'];					$result0['goldafter'] = (int)$buyer_gold;					$result0['diamond'] = (int)$order['diamond'];					$result0['diamondafter'] = (int)$buyer_diamond;					$result0['desc'] = "购买成功,您获得了".$showgold."万金币";					return $this->answerResquest('1','',$result0);									}else{					return $this->answerResquest('-1', '订单生成异常，请联系客服');				} 		}	}	}